# @package _global_
# Config for running on workstations with two 40gb+ GPUs, see TUTORIAL
# for extra instructions. In short, use cmd line arg "+deploy=local_2gpus" with wizard.

defaults:
  - _self_
  - /stable_manifest/internal

defines:
  # The repo-relative resolver makes the path relative to the git repo root.
  filesystem: ${repo-relative:"data"}

services:
  driver:
    replicas_per_container: 1
    gpus: [0, 1]

  sensorsim:
    replicas_per_container: 1
    gpus: [0, 1]

  physics:
    replicas_per_container: 1
    gpus: [0, 1]

  trafficsim:
    replicas_per_container: 1
    gpus: [0, 1]

  controller:
    replicas_per_container: 2
    gpus: null
